// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Public               string   `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	Private              string   `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	PublicVersion        string   `protobuf:"bytes,4,opt,name=publicVersion,proto3" json:"publicVersion,omitempty"`
	Format               string   `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	PublicFormat         string   `protobuf:"bytes,6,opt,name=publicFormat,proto3" json:"publicFormat,omitempty"`
	Services             string   `protobuf:"bytes,7,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Config) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *Config) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *Config) GetPublicVersion() string {
	if m != nil {
		return m.PublicVersion
	}
	return ""
}

func (m *Config) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Config) GetPublicFormat() string {
	if m != nil {
		return m.PublicFormat
	}
	return ""
}

func (m *Config) GetServices() string {
	if m != nil {
		return m.Services
	}
	return ""
}

type ConfigVersion struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	GroupId              string   `protobuf:"bytes,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	PublicVersion        string   `protobuf:"bytes,4,opt,name=publicVersion,proto3" json:"publicVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigVersion) Reset()         { *m = ConfigVersion{} }
func (m *ConfigVersion) String() string { return proto.CompactTextString(m) }
func (*ConfigVersion) ProtoMessage()    {}
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{1}
}
func (m *ConfigVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigVersion.Unmarshal(m, b)
}
func (m *ConfigVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigVersion.Marshal(b, m, deterministic)
}
func (dst *ConfigVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigVersion.Merge(dst, src)
}
func (m *ConfigVersion) XXX_Size() int {
	return xxx_messageInfo_ConfigVersion.Size(m)
}
func (m *ConfigVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigVersion proto.InternalMessageInfo

func (m *ConfigVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConfigVersion) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ConfigVersion) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *ConfigVersion) GetPublicVersion() string {
	if m != nil {
		return m.PublicVersion
	}
	return ""
}

type PublishConfigRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	Private              string   `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	TagName              string   `protobuf:"bytes,5,opt,name=TagName,proto3" json:"TagName,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishConfigRequest) Reset()         { *m = PublishConfigRequest{} }
func (m *PublishConfigRequest) String() string { return proto.CompactTextString(m) }
func (*PublishConfigRequest) ProtoMessage()    {}
func (*PublishConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{2}
}
func (m *PublishConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishConfigRequest.Unmarshal(m, b)
}
func (m *PublishConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishConfigRequest.Marshal(b, m, deterministic)
}
func (dst *PublishConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishConfigRequest.Merge(dst, src)
}
func (m *PublishConfigRequest) XXX_Size() int {
	return xxx_messageInfo_PublishConfigRequest.Size(m)
}
func (m *PublishConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishConfigRequest proto.InternalMessageInfo

func (m *PublishConfigRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PublishConfigRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *PublishConfigRequest) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *PublishConfigRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *PublishConfigRequest) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func (m *PublishConfigRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type PutConfigRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	HeartBeatPackage     string   `protobuf:"bytes,3,opt,name=HeartBeatPackage,proto3" json:"HeartBeatPackage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutConfigRequest) Reset()         { *m = PutConfigRequest{} }
func (m *PutConfigRequest) String() string { return proto.CompactTextString(m) }
func (*PutConfigRequest) ProtoMessage()    {}
func (*PutConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{4}
}
func (m *PutConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutConfigRequest.Unmarshal(m, b)
}
func (m *PutConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutConfigRequest.Marshal(b, m, deterministic)
}
func (dst *PutConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutConfigRequest.Merge(dst, src)
}
func (m *PutConfigRequest) XXX_Size() int {
	return xxx_messageInfo_PutConfigRequest.Size(m)
}
func (m *PutConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutConfigRequest proto.InternalMessageInfo

func (m *PutConfigRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PutConfigRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *PutConfigRequest) GetHeartBeatPackage() string {
	if m != nil {
		return m.HeartBeatPackage
	}
	return ""
}

type UpdateConfigMessage struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigMessage) Reset()         { *m = UpdateConfigMessage{} }
func (m *UpdateConfigMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigMessage) ProtoMessage()    {}
func (*UpdateConfigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{5}
}
func (m *UpdateConfigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigMessage.Unmarshal(m, b)
}
func (m *UpdateConfigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigMessage.Marshal(b, m, deterministic)
}
func (dst *UpdateConfigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigMessage.Merge(dst, src)
}
func (m *UpdateConfigMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigMessage.Size(m)
}
func (m *UpdateConfigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigMessage proto.InternalMessageInfo

func (m *UpdateConfigMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateConfigMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutConfigResponse struct {
	Config               *Config              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	UpdateConfigMessage  *UpdateConfigMessage `protobuf:"bytes,2,opt,name=updateConfigMessage,proto3" json:"updateConfigMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutConfigResponse) Reset()         { *m = PutConfigResponse{} }
func (m *PutConfigResponse) String() string { return proto.CompactTextString(m) }
func (*PutConfigResponse) ProtoMessage()    {}
func (*PutConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_3f16a8cb24ed0677, []int{6}
}
func (m *PutConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutConfigResponse.Unmarshal(m, b)
}
func (m *PutConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutConfigResponse.Marshal(b, m, deterministic)
}
func (dst *PutConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutConfigResponse.Merge(dst, src)
}
func (m *PutConfigResponse) XXX_Size() int {
	return xxx_messageInfo_PutConfigResponse.Size(m)
}
func (m *PutConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutConfigResponse proto.InternalMessageInfo

func (m *PutConfigResponse) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *PutConfigResponse) GetUpdateConfigMessage() *UpdateConfigMessage {
	if m != nil {
		return m.UpdateConfigMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "proto.Config")
	proto.RegisterType((*ConfigVersion)(nil), "proto.ConfigVersion")
	proto.RegisterType((*PublishConfigRequest)(nil), "proto.PublishConfigRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*PutConfigRequest)(nil), "proto.PutConfigRequest")
	proto.RegisterType((*UpdateConfigMessage)(nil), "proto.UpdateConfigMessage")
	proto.RegisterType((*PutConfigResponse)(nil), "proto.PutConfigResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigServiceClient interface {
	GetConfig(ctx context.Context, in *ConfigVersion, opts ...grpc.CallOption) (*Config, error)
	ListenConfig(ctx context.Context, opts ...grpc.CallOption) (ConfigService_ListenConfigClient, error)
	PublishConfig(ctx context.Context, in *PublishConfigRequest, opts ...grpc.CallOption) (*Response, error)
	PutConfig(ctx context.Context, opts ...grpc.CallOption) (ConfigService_PutConfigClient, error)
	DeleteMessage(ctx context.Context, in *UpdateConfigMessage, opts ...grpc.CallOption) (*Response, error)
}

type configServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigServiceClient(cc *grpc.ClientConn) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetConfig(ctx context.Context, in *ConfigVersion, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/proto.ConfigService/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListenConfig(ctx context.Context, opts ...grpc.CallOption) (ConfigService_ListenConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigService_serviceDesc.Streams[0], "/proto.ConfigService/ListenConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &configServiceListenConfigClient{stream}
	return x, nil
}

type ConfigService_ListenConfigClient interface {
	Send(*ConfigVersion) error
	Recv() (*Config, error)
	grpc.ClientStream
}

type configServiceListenConfigClient struct {
	grpc.ClientStream
}

func (x *configServiceListenConfigClient) Send(m *ConfigVersion) error {
	return x.ClientStream.SendMsg(m)
}

func (x *configServiceListenConfigClient) Recv() (*Config, error) {
	m := new(Config)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configServiceClient) PublishConfig(ctx context.Context, in *PublishConfigRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ConfigService/PublishConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) PutConfig(ctx context.Context, opts ...grpc.CallOption) (ConfigService_PutConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigService_serviceDesc.Streams[1], "/proto.ConfigService/PutConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &configServicePutConfigClient{stream}
	return x, nil
}

type ConfigService_PutConfigClient interface {
	Send(*PutConfigRequest) error
	Recv() (*PutConfigResponse, error)
	grpc.ClientStream
}

type configServicePutConfigClient struct {
	grpc.ClientStream
}

func (x *configServicePutConfigClient) Send(m *PutConfigRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *configServicePutConfigClient) Recv() (*PutConfigResponse, error) {
	m := new(PutConfigResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configServiceClient) DeleteMessage(ctx context.Context, in *UpdateConfigMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ConfigService/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
type ConfigServiceServer interface {
	GetConfig(context.Context, *ConfigVersion) (*Config, error)
	ListenConfig(ConfigService_ListenConfigServer) error
	PublishConfig(context.Context, *PublishConfigRequest) (*Response, error)
	PutConfig(ConfigService_PutConfigServer) error
	DeleteMessage(context.Context, *UpdateConfigMessage) (*Response, error)
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConfigService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfig(ctx, req.(*ConfigVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListenConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigServiceServer).ListenConfig(&configServiceListenConfigServer{stream})
}

type ConfigService_ListenConfigServer interface {
	Send(*Config) error
	Recv() (*ConfigVersion, error)
	grpc.ServerStream
}

type configServiceListenConfigServer struct {
	grpc.ServerStream
}

func (x *configServiceListenConfigServer) Send(m *Config) error {
	return x.ServerStream.SendMsg(m)
}

func (x *configServiceListenConfigServer) Recv() (*ConfigVersion, error) {
	m := new(ConfigVersion)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ConfigService_PublishConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).PublishConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConfigService/PublishConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).PublishConfig(ctx, req.(*PublishConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_PutConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigServiceServer).PutConfig(&configServicePutConfigServer{stream})
}

type ConfigService_PutConfigServer interface {
	Send(*PutConfigResponse) error
	Recv() (*PutConfigRequest, error)
	grpc.ServerStream
}

type configServicePutConfigServer struct {
	grpc.ServerStream
}

func (x *configServicePutConfigServer) Send(m *PutConfigResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *configServicePutConfigServer) Recv() (*PutConfigRequest, error) {
	m := new(PutConfigRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ConfigService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConfigService/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteMessage(ctx, req.(*UpdateConfigMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ConfigService_GetConfig_Handler,
		},
		{
			MethodName: "PublishConfig",
			Handler:    _ConfigService_PublishConfig_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _ConfigService_DeleteMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenConfig",
			Handler:       _ConfigService_ListenConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PutConfig",
			Handler:       _ConfigService_PutConfig_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "config.proto",
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_3f16a8cb24ed0677) }

var fileDescriptor_config_3f16a8cb24ed0677 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xae, 0xd3, 0x66, 0xd3, 0x4c, 0xb2, 0x22, 0xb8, 0x11, 0xac, 0x96, 0x4b, 0x65, 0x81, 0x54,
	0x71, 0xa8, 0x50, 0x38, 0x71, 0x00, 0x24, 0x88, 0x28, 0x48, 0x05, 0x45, 0xe1, 0xe7, 0xee, 0x6e,
	0xa7, 0x61, 0xd5, 0x34, 0xbb, 0xd8, 0xde, 0x48, 0xf0, 0x04, 0x48, 0xbc, 0x14, 0x17, 0x5e, 0x80,
	0x27, 0x42, 0x6b, 0x8f, 0x43, 0x4c, 0xb6, 0x11, 0x48, 0x9c, 0x92, 0x6f, 0xc6, 0x33, 0xdf, 0xcf,
	0xda, 0xd0, 0xcf, 0x8a, 0xc5, 0x45, 0x3e, 0x3b, 0x2e, 0x55, 0x61, 0x0a, 0xde, 0xb6, 0x3f, 0xe2,
	0x27, 0x83, 0xe8, 0xb9, 0xad, 0xf3, 0x04, 0x3a, 0x4b, 0x54, 0x3a, 0x2f, 0x16, 0x09, 0x3b, 0x64,
	0x47, 0xdd, 0xa9, 0x87, 0xfc, 0x16, 0x44, 0x65, 0x75, 0x36, 0xcf, 0xb3, 0xa4, 0x65, 0x1b, 0x84,
	0xea, 0x89, 0x52, 0xe5, 0x4b, 0x69, 0x30, 0xd9, 0x75, 0x13, 0x04, 0xf9, 0x5d, 0x88, 0xdd, 0x99,
	0x0f, 0xb4, 0x71, 0xcf, 0xf6, 0xc3, 0x62, 0xbd, 0xf7, 0xa2, 0x50, 0x57, 0xd2, 0x24, 0x6d, 0xb7,
	0xd7, 0x21, 0x2e, 0xa0, 0xef, 0x0e, 0xbe, 0x70, 0xdd, 0xc8, 0x76, 0x83, 0x1a, 0x4f, 0x61, 0x5f,
	0xa3, 0x5a, 0xe6, 0x19, 0xea, 0xa4, 0x63, 0xfb, 0x2b, 0x2c, 0xbe, 0x31, 0x88, 0x9d, 0x29, 0xcf,
	0x74, 0xbd, 0xb7, 0x43, 0xe8, 0xbd, 0x75, 0x73, 0x6f, 0xe4, 0x15, 0x92, 0xc1, 0xf5, 0x52, 0x3d,
	0x7b, 0xa2, 0x8a, 0xaa, 0x7c, 0x75, 0xee, 0x5d, 0x12, 0xfc, 0x3b, 0x97, 0xe2, 0x3b, 0x83, 0xe1,
	0xa4, 0xae, 0xe8, 0x8f, 0x4e, 0xd4, 0x14, 0x3f, 0x55, 0xa8, 0xcd, 0x9f, 0xd4, 0x6c, 0x2b, 0x75,
	0x2b, 0xa4, 0xbe, 0x3e, 0xfa, 0xdf, 0xa1, 0xee, 0x05, 0xa1, 0x26, 0xd0, 0x79, 0x27, 0x67, 0x96,
	0xc9, 0xa5, 0xed, 0x61, 0xad, 0x63, 0x8c, 0x3a, 0x53, 0x79, 0x69, 0x6a, 0x13, 0x2e, 0xed, 0xf5,
	0x92, 0x10, 0xb0, 0x3f, 0x45, 0x5d, 0x16, 0x0b, 0x6d, 0xf7, 0x2b, 0xd4, 0xd5, 0xdc, 0x90, 0x60,
	0x42, 0xe2, 0x0b, 0x0c, 0x26, 0x95, 0xf9, 0x7f, 0x0e, 0xef, 0xc3, 0xe0, 0x25, 0x4a, 0x65, 0x9e,
	0xa1, 0x34, 0x13, 0x99, 0x5d, 0xca, 0x99, 0xb7, 0xba, 0x51, 0x17, 0x8f, 0xe1, 0xe0, 0x7d, 0x79,
	0x2e, 0x0d, 0x3a, 0xfa, 0xd7, 0xa8, 0xb5, 0x9c, 0x21, 0x1f, 0xc0, 0xee, 0x25, 0x7e, 0x26, 0xda,
	0xfa, 0x2f, 0x1f, 0x42, 0x7b, 0x29, 0xe7, 0x95, 0xff, 0xce, 0x0e, 0x88, 0xaf, 0x0c, 0x6e, 0xae,
	0x69, 0x27, 0xa3, 0xf7, 0x20, 0x72, 0x2f, 0xc6, 0x2e, 0xe8, 0x8d, 0x62, 0xf7, 0x72, 0x8e, 0xe9,
	0x18, 0x35, 0xf9, 0x29, 0x1c, 0x54, 0x9b, 0xdc, 0x96, 0xa0, 0x37, 0x4a, 0x69, 0xa6, 0x41, 0xdd,
	0xb4, 0x69, 0x6c, 0xf4, 0xa3, 0xe5, 0xaf, 0x2e, 0xa5, 0xc4, 0x47, 0xd0, 0x3d, 0x41, 0xd2, 0xc6,
	0x87, 0x81, 0x06, 0xba, 0x61, 0x69, 0xa8, 0x4c, 0xec, 0xf0, 0x47, 0xd0, 0x3f, 0xcd, 0xb5, 0xc1,
	0xc5, 0x3f, 0x8d, 0x1d, 0xb1, 0x07, 0x8c, 0x3f, 0x85, 0x38, 0xb8, 0xac, 0xfc, 0x0e, 0x9d, 0x6a,
	0xba, 0xc2, 0xe9, 0x0d, 0x6a, 0xfa, 0xd0, 0xc4, 0x0e, 0x1f, 0x43, 0x77, 0x95, 0x25, 0xbf, 0xbd,
	0x1a, 0x0e, 0x6f, 0x46, 0x9a, 0x6c, 0x36, 0xfc, 0x06, 0x2b, 0xe3, 0x09, 0xc4, 0x63, 0x9c, 0xa3,
	0x41, 0xff, 0x2d, 0xb7, 0x24, 0xd9, 0xa0, 0xe2, 0x2c, 0xb2, 0x95, 0x87, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0x2a, 0x93, 0xb8, 0xf5, 0x04, 0x00, 0x00,
}
